### ISSUE TITLE
Components of an experimental setup

### ISSUE THREAD

**Issue by simonduq** [iot-benchmark/iot-benchmark.github.io#8]
The current proposal (https://github.com/iot-benchmark/iot-benchmark.github.io/wiki/Data-Schema#experimental-setup---base-components) defines *radio*, *platform* and *environment* as distinct entities. While this might feel neat, I'm not sure it is worth the added complexity (of adding and maintaining a radio, platform and env every time a new testbed/simulation is added/modified).

Isn't it sufficient to just have environment (e.g. "Flocklab") and then as part of the *result*, where we already provide a list of nodes, also specify the platform&radio?

**Comment by romain-jacob** [comment]
Fundamentally, I don't think it makes much difference to have radio/platform within the 'environment' or the 'results', if it remains a compulsory information to provide. A agree it adds a level of complexity that might not be needed.

In my opinion, the radio **must** be part of the description (somewhere). Then I thought: if I take the cc2538, it is on the OpenMote, the firefly, the OpenMoteB... if we don't specify the platform, we may end-up comparing results that used the same radio chip but otherwise different hardware. Although this may be perfectly fine for some metrics (say PRR), one may want to be more careful with others (like energy consumption for example)...

That's why I ended up having both in. But like the rest, this is only a proposal

**Comment by simonduq** [comment]
OK we had a discussion offline, and decided for now to make "xp setup" composed of "environment" and "platform", but remove "radio chip". This is ofc not final -- things can be (re)added at a later stage.
